import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,ChevronRight,ScanLine,ShieldCheck,TrendingUp,WalletCards,RefreshCw,Wifi,WifiOff,Search,Info,Clock3,FlaskConical,Trophy}from'lucide-react';
import'./styles.css';
type B={bookmakerID:string;odds:number;openOdds:number|null;deeplink:string|null;excluded?:boolean};
type O={oddID:string|null;marketName:string|null;sideID:string|null;fairOdds:number|null;fairProbability:number|null;bestBook:B|null;edge:number|null;ev:number|null;books:B[];integrity?:string;validBooks?:number;totalBooks?:number;rejectedBooks?:string[]};
type E={eventID:string;leagueID:string;startTime:string|null;home:{name:string};away:{name:string};moneyline:{home:O|null;away:O|null};markets:O[]};
type F={ok:boolean;provider?:string;fetchedAt?:string;events?:E[];error?:string;code?:string};
type Intel={ok:boolean;provider?:string;updatedAt?:string;fighters?:{away:any;home:any};history?:{away:any[];home:any[]};comparison?:any;model?:any;error?:string;code?:string};
const fo=(n:number|null|undefined)=>n==null?'—':(n>0?'+':'')+n;
const sn=(n:number|null|undefined)=>n==null?'—':(n>=0?'+':'')+n.toFixed(1)+'%';
const bn=(s:string)=>(s||'').replace(/[_-]/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const method=(s:any)=>({ko_tko:'KO/TKO',ko:'KO/TKO',submission:'Submission',sub:'Submission',decision_unanimous:'Unanimous Decision',decision_split:'Split Decision',decision_majority:'Majority Decision',decision:'Decision',no_contest:'No Contest'}[String(s||'').toLowerCase()]||bn(String(s||'—')));
const pp=(n:any)=>n==null?'—':(Number(n)*100).toFixed(1)+'%';
const matchupWriteup=(e:E,m:any)=>{if(!m)return[];const af=m.features?.away||{},hf=m.features?.home||{},fav=m.awayWin>=m.homeWin?e.away.name:e.home.name,dog=m.awayWin>=m.homeWin?e.home.name:e.away.name,fp=Math.max(m.awayWin,m.homeWin);const striking=af.slpm&&hf.slpm?(af.slpm>hf.slpm?e.away.name:e.home.name)+' has the higher recorded striking output.':'Recorded striking rates are incomplete, so the model is not treating striking volume as decisive.';const grap=af.tdAvg!=null&&hf.tdAvg!=null?(af.tdAvg>hf.tdAvg?e.away.name:e.home.name)+' shows the stronger takedown-volume profile, but matchup defense still matters more than raw attempts.':'The grappling data is too incomplete to call a clear wrestling-volume edge.';return[{t:'Fight read',x:`${fav} is the baseline side at ${pp(fp)}, but the gap is not large enough to treat ${dog} as an afterthought. The read is matchup-driven rather than a simple record comparison.`},{t:'Striking matchup',x:striking},{t:'Grappling matchup',x:grap},{t:'Career context',x:'CageCash now uses a deeper career sample. UFC results receive extra weight for competition quality, while pre-UFC, regional and international fights remain part of form, finishing tendencies and experience.'},{t:'What can flip it',x:'MMA remains high variance. A style change, early knockdown, wrestling success, short-notice issue or durability failure can overwhelm the statistical baseline.'}]};
const who=(e:E,m:O)=>m.sideID==='home'?e.home.name:m.sideID==='away'?e.away.name:(m.marketName||'Market');
const time=(s:string|null)=>s?new Date(s).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Time TBD';
function App(){const[tab,setTab]=useState('Desk'),[feed,setFeed]=useState<F|null>(null),[loading,setLoading]=useState(true),[sel,setSel]=useState<E|null>(null),[intel,setIntel]=useState<Intel|null>(null),[intelLoading,setIntelLoading]=useState(false),[q,setQ]=useState(''),[bank]=useState(1000);
const load=async()=>{setLoading(true);try{const r=await fetch('/api/mma',{cache:'no-store'});setFeed(await r.json())}catch(e){setFeed({ok:false,error:e instanceof Error?e.message:'Feed error'})}finally{setLoading(false)}};useEffect(()=>{load()},[]);
useEffect(()=>{if(!sel){setIntel(null);return}setIntelLoading(true);fetch('/api/ufcal?a='+encodeURIComponent(sel.away.name)+'&b='+encodeURIComponent(sel.home.name),{cache:'no-store'}).then(r=>r.json()).then(setIntel).catch(e=>setIntel({ok:false,error:e.message})).finally(()=>setIntelLoading(false))},[sel]);
const events=feed?.events||[];const rows=useMemo(()=>events.flatMap(e=>e.markets.filter(m=>m.bestBook&&m.fairOdds!=null).map(m=>({e,m}))).filter(x=>(x.e.away.name+' '+x.e.home.name+' '+(x.m.marketName||'')).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>(b.m.ev??-999)-(a.m.ev??-999)),[events,q]);
if(sel){const a=sel.moneyline.away,h=sel.moneyline.home;const best=[a,h].filter(Boolean).sort((x,y)=>(y?.ev??-999)-(x?.ev??-999))[0]||null;const verdict=!intel?.model?'MODEL PENDING':intel.model.confidence==='LOW'?'PASS':(Math.max(intel.model.awayWin,intel.model.homeWin)>=.60?'MODEL LEAN':'PASS');const A=intel?.fighters?.away,H=intel?.fighters?.home;const rec=(x:any)=>x?.record||x?.records?.pro_mma?.value||x?.records?.['pro-mma']?.value||'—';return <main><header><button className='back' onClick={()=>setSel(null)}>‹</button><div className='brand'>CAGECASH</div><span/></header><section><div className='sectionhead'><div><small>FIGHT INTELLIGENCE</small><h2>{sel.away.name} vs {sel.home.name}</h2></div></div><div className='meta'><Clock3/> {time(sel.startTime)}</div>
<div className='verdict'><small>CAGECASH BETTING VERDICT</small><strong className={verdict==='MODEL LEAN'?'good':verdict==='PASS'?'bad':''}>{verdict}</strong><p>{intel?.model?'Baseline model favors '+(intel.model.awayWin>=intel.model.homeWin?sel.away.name:sel.home.name)+' at '+pp(Math.max(intel.model.awayWin,intel.model.homeWin))+'. This is a model read, not a validated betting recommendation.':'Loading independent fighter model…'}</p></div>
<div className='intel'><div className='intelhead'><span>FIGHTER DATA</span><b>{intelLoading?'Loading…':intel?.ok?'UFCalendar connected':'Unavailable'}</b></div>{intelLoading?<div className='lab'><RefreshCw className='spin'/><h3>Building fighter dossier…</h3></div>:intel?.ok?<><div className='profiles'><div><small>AWAY</small><h3>{A?.name||sel.away.name}</h3><b>{rec(A)}</b><p>{[A?.age&&'Age '+A.age,A?.height_display||A?.height,A?.reach_display||A?.reach,A?.stance].filter(Boolean).join(' · ')||'Profile loaded'}</p></div><div className='right'><small>HOME</small><h3>{H?.name||sel.home.name}</h3><b>{rec(H)}</b><p>{[H?.age&&'Age '+H.age,H?.height_display||H?.height,H?.reach_display||H?.reach,H?.stance].filter(Boolean).join(' · ')||'Profile loaded'}</p></div></div><div className='history'><h3>Recent fight history</h3>{[['away',sel.away.name],['home',sel.home.name]].map(([side,name]:any)=><div className='historycol' key={side}><b>{name}</b>{(intel.history?.[side]||[]).slice(0,5).map((x:any,k:number)=><p key={k}><strong>{String(x.status||x.result||'—').toUpperCase()}</strong> {x.opponent||'Opponent'} <span>{method(x.method)}{x.round?' · Round '+x.round:''}</span></p>)}</div>)}</div></>:<div className='warning'><Info/><p><b>Fighter intelligence unavailable.</b> {intel?.error||'This matchup could not be matched to the historical database.'} CageCash will not invent a model prediction.</p></div>}</div>
<div className='modelcard'><small>CAGECASH MODEL · BASELINE V1.2</small>{intel?.model?<><h3>{intel.model.awayWin>=intel.model.homeWin?sel.away.name:sel.home.name} · {pp(Math.max(intel.model.awayWin,intel.model.homeWin))}</h3><div className='probars'><div><span>{sel.away.name}</span><b>{pp(intel.model.awayWin)}</b><i><em style={{width:pp(intel.model.awayWin)}}/></i></div><div><span>{sel.home.name}</span><b>{pp(intel.model.homeWin)}</b><i><em style={{width:pp(intel.model.homeWin)}}/></i></div></div><div className='simstats'><div><small>SIMULATIONS</small><b>{Number(intel.model.simulationCount).toLocaleString()}</b></div><div><small>DATA QUALITY</small><b>{intel.model.quality}/100</b></div><div><small>CONFIDENCE</small><b>{intel.model.confidence}</b></div></div><div className='careerctx'><b>Career sample</b><span>Up to 20 completed fights per fighter · UFC weighted, not UFC-only</span></div><div className='methods'><b>Projected win paths</b><p>{sel.away.name}: KO/TKO {pp(intel.model.awayMethod?.ko_tko)} · SUB {pp(intel.model.awayMethod?.submission)} · DEC {pp(intel.model.awayMethod?.decision)}</p><p>{sel.home.name}: KO/TKO {pp(intel.model.homeMethod?.ko_tko)} · SUB {pp(intel.model.homeMethod?.submission)} · DEC {pp(intel.model.homeMethod?.decision)}</p></div><div className='breakdown'><h3>Matchup breakdown</h3>{matchupWriteup(sel,intel.model).map((x:any)=><div key={x.t}><b>{x.t}</b><p>{x.x}</p></div>)}</div><p className='modelwarn'>Baseline independent model — not yet backtested/calibrated for wagering. Probabilities are kept separate from sportsbook consensus.</p></>:<><h3>Waiting for fighter data</h3><p>CageCash will not generate a prediction without sufficient historical data.</p></>}</div>
<div className='sectionhead'><div><small>MARKET</small><h2>Sportsbook board</h2></div><span>Secondary to analysis</span></div>{sel.markets.filter(m=>m.bestBook).sort((a,b)=>(b.ev??-999)-(a.ev??-999)).map(m=><article className='market' key={m.oddID||m.sideID||'market'}><div className='fighttop'><span>{who(sel,m)}</span><b className={(m.ev??-1)>0?'good':'bad'}>{sn(m.ev)} consensus EV</b></div><div className='grid'><div><span>Market fair</span><b>{fo(m.fairOdds)}</b></div><div><span>Best price</span><b>{fo(m.bestBook?.odds)}</b></div><div><span>Book</span><b>{bn(m.bestBook?.bookmakerID||'')}</b></div><div><span>Price edge</span><b>{sn(m.edge)}</b></div></div><div className='integrity'><b>{m.integrity==='GOOD'?'✓ Odds integrity checked':'⚠ Market needs caution'}</b><span>{m.validBooks||0}/{m.totalBooks||0} books used for consensus</span></div><div className='books'>{m.books.slice(0,8).map(b=><div className={b.excluded?'excluded':''} key={b.bookmakerID}><span>{bn(b.bookmakerID)}{b.excluded?' · excluded':''}</span><b>{fo(b.odds)}</b></div>)}</div></article>)}</section></main>}
return <main><header><div className='brand'><span className='mark'>⬡</span>CAGECASH</div><div className='headright'><span className={feed?.ok?'status on':'status'}>{feed?.ok?<Wifi/>:<WifiOff/>}</span><button className='bank'><WalletCards size={16}/>${bank.toLocaleString()}</button></div></header>
{tab==='Desk'&&<><section className='hero'><div className='eyebrow'><Activity size={14}/> LIVE MMA DESK</div><h1>Real lines, <span>priced smarter.</span></h1><p>Live MMA markets, sportsbook prices, no-vig fair odds and expected-value scanning through a protected server endpoint.</p><div className='pills'><b>LIVE MMA</b><span>NO-VIG FAIR</span><span>BOOK SHOPPING</span></div><div className='actions'><button onClick={()=>document.getElementById('board')?.scrollIntoView({behavior:'smooth'})}>Open board <ChevronRight/></button><button className='ghost' onClick={()=>setTab('Scanner')}><ScanLine/> Value scanner</button></div></section>
<div className='feed'><div>{loading?<RefreshCw className='spin'/>:feed?.ok?<Wifi/>:<WifiOff/>}<span><b>{loading?'Refreshing…':feed?.ok?'Live feed connected':'Feed needs attention'}</b><small>{feed?.ok?events.length+' MMA events · '+feed.provider:(feed?.error||'Waiting for feed')}</small></span></div><button onClick={load}><RefreshCw/></button></div>
<section className='snapshot'><div><small>EVENTS</small><strong>{events.length}</strong><em>with odds</em></div><div><small>TOP EV</small><strong>{rows[0]?sn(rows[0].m.ev):'—'}</strong><em>best listed</em></div><div><small>ENGINE</small><strong>{feed?.ok?'LIVE':'OFF'}</strong><em>server-side</em></div></section>
<section id='board'><div className='sectionhead'><div><small>THE DESK</small><h2>Upcoming fights</h2></div><span>Tap for all books</span></div>{loading&&<div className='lab'><RefreshCw className='spin'/><h3>Loading MMA markets…</h3></div>}{!loading&&!feed?.ok&&<div className='setup'><WifiOff/><h3>{feed?.code==='KEY_MISSING'?'Add API key in Vercel':'Feed could not load'}</h3><p>{feed?.error}</p>{feed?.code==='KEY_MISSING'&&<code>SPORTSGAMEODDS_API_KEY</code>}</div>}{!loading&&feed?.ok&&!events.length&&<div className='lab'><h3>No open MMA markets</h3><p>The feed is connected but currently returned no priced events.</p></div>}{events.map(e=><Fight e={e} open={setSel} key={e.eventID}/>)}</section></>}
{tab==='Picks'&&<section><div className='sectionhead'><div><small>CAGECASH CARD READS</small><h2>Best bets & picks</h2></div></div><p className='intro'>This board is for the strongest fight reads, not simply the biggest mathematical EV. Model confidence, matchup reliability and price will drive these rankings once calibration is live.</p><div className='warning'><Info/><p><b>Independent picks are not live yet.</b> Fighter history is connected, but CageCash will not manufacture best bets from sportsbook consensus. This board will populate from the validated model.</p></div><div className='lab'><Trophy/><h3>Calibration gate active</h3><p>Market-consensus EV is no longer promoted as a CageCash pick. This board will unlock model-ranked bets after backtesting and calibration.</p></div></section>}
{tab==='Scanner'&&<section><div className='sectionhead'><div><small>VALUE SCANNER</small><h2>Best prices vs fair</h2></div></div><p className='intro'>Real markets ranked by expected value versus consensus no-vig fair odds.</p><div className='search'><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Search fighter or market'/></div>{rows.slice(0,100).map(({e,m})=><div className='scan' key={e.eventID+':'+m.oddID} onClick={()=>setSel(e)}><div><small>{e.away.name} vs {e.home.name}</small><b>{who(e,m)}</b><span>{m.marketName||'Market'} · fair {fo(m.fairOdds)} · {bn(m.bestBook?.bookmakerID||'')} {fo(m.bestBook?.odds)}</span></div><strong className={(m.ev??-1)>0?'good':'bad'}>{sn(m.ev)}</strong></div>)}</section>}
{tab==='Lab'&&<section><div className='sectionhead'><div><small>BET LAB</small><h2>Pricing workspace</h2></div></div><div className='lab'><FlaskConical/><h3>Live markets first</h3><p>Baseline V1.1 is now connected to fighter history. This workspace is reserved for calibrated simulations, sensitivity testing and method/round distributions as the model graduates.</p></div></section>}
{tab==='Model'&&<section><div className='sectionhead'><div><small>MODEL</small><h2>Engine status</h2></div></div><div className='model'><ShieldCheck/><h3>Live odds layer: {feed?.ok?'Operational':'Waiting'}</h3><p>Automatic MMA events, bookmaker prices and robust consensus pricing are live. Outlier books are excluded from fair-price and best-price calculations when they disagree sharply with the dominant market cluster.</p><p className='note'>Independent Baseline V1.2 is connected to UFCalendar fighter history and kept separate from sportsbook consensus. Odds integrity filtering is active. The next gate is historical backtesting and probability calibration before model outputs become official CageCash picks.</p></div></section>}
<nav>{[['Desk',Activity],['Picks',Trophy],['Scanner',ScanLine],['Lab',FlaskConical],['Model',TrendingUp]].map(([n,I]:any)=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I size={19}/><span>{n}</span></button>)}</nav></main>}
function Fight({e,open}:{e:E;open:(e:E)=>void}){const a=e.moneyline.away,h=e.moneyline.home;const top=[a,h].filter(Boolean).sort((x,y)=>(y?.ev??-999)-(x?.ev??-999))[0]||null;return <article className='fight' onClick={()=>open(e)}><div className='fighttop'><span>{e.leagueID||'MMA'}</span><b className={(top?.ev??-1)>0?'good':'bad'}>{top?sn(top.ev)+' EV':'LIVE'}</b></div><div className='names'><div><small>AWAY</small><h3>{e.away.name}</h3><p>{fo(a?.bestBook?.odds)}</p></div><div className='vs'>VS</div><div className='right'><small>HOME</small><h3>{e.home.name}</h3><p>{fo(h?.bestBook?.odds)}</p></div></div><div className='meta'><Clock3/> {time(e.startTime)}</div>{top&&<div className='pick'><span>{(top.ev??-1)>0?'Market value':'No bet'}</span><b>{who(e,top)} · fair {fo(top.fairOdds)}</b><ChevronRight size={18}/></div>}</article>}
createRoot(document.getElementById('root')!).render(<App/>);